<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		
    	//Ingreso de Paises a la base de datos


DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (1, 'AF', 'Afghanistan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (2, 'AL', 'Albania',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (3, 'DZ', 'Algeria',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (4, 'AS', 'American Samoa',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (5, 'AD', 'Andorra',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (6, 'AO', 'Angola',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (7, 'AI', 'Anguilla',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (8, 'AQ', 'Antarctica',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (9, 'AG', 'Antigua And Barbuda',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (10, 'AR', 'Argentina',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (11, 'AM', 'Armenia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (12, 'AW', 'Aruba',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (13, 'AU', 'Australia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (14, 'AT', 'Austria',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (15, 'AZ', 'Azerbaijan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (16, 'BS', 'Bahamas The',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (17, 'BH', 'Bahrain',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (18, 'BD', 'Bangladesh',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (19, 'BB', 'Barbados',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (20, 'BY', 'Belarus',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (21, 'BE', 'Belgium',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (22, 'BZ', 'Belize',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (23, 'BJ', 'Benin',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (24, 'BM', 'Bermuda',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (25, 'BT', 'Bhutan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (26, 'BO', 'Bolivia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (27, 'BA', 'Bosnia and Herzegovina',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (28, 'BW', 'Botswana',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (29, 'BV', 'Bouvet Island',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (30, 'BR', 'Brazil',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (31, 'IO', 'British Indian Ocean Territory',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (32, 'BN', 'Brunei',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (33, 'BG', 'Bulgaria',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (34, 'BF', 'Burkina Faso',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (35, 'BI', 'Burundi',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (36, 'KH', 'Cambodia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (37, 'CM', 'Cameroon',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (38, 'CA', 'Canada',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (39, 'CV', 'Cape Verde',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (40, 'KY', 'Cayman Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (41, 'CF', 'Central African Republic',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (42, 'TD', 'Chad',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (43, 'CL', 'Chile',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (44, 'CN', 'China',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (45, 'CX', 'Christmas Island',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (46, 'CC', 'Cocos (Keeling) Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (47, 'CO', 'Colombia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (48, 'KM', 'Comoros',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (49, 'CG', 'Republic Of The Congo',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (50, 'CD', 'Democratic Republic Of The Congo',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (51, 'CK', 'Cook Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (52, 'CR', 'Costa Rica',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (53, 'CI', 'Cote D\'Ivoire (Ivory Coast)',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (54, 'HR', 'Croatia (Hrvatska)',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (55, 'CU', 'Cuba',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (56, 'CY', 'Cyprus',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (57, 'CZ', 'Czech Republic',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (58, 'DK', 'Denmark',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (59, 'DJ', 'Djibouti',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (60, 'DM', 'Dominica',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (61, 'DO', 'Dominican Republic',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (62, 'TP', 'East Timor',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (63, 'EC', 'Ecuador',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (64, 'EG', 'Egypt',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (65, 'SV', 'El Salvador',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (66, 'GQ', 'Equatorial Guinea',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (67, 'ER', 'Eritrea',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (68, 'EE', 'Estonia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (69, 'ET', 'Ethiopia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (70, 'XA', 'External Territories of Australia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (71, 'FK', 'Falkland Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (72, 'FO', 'Faroe Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (73, 'FJ', 'Fiji Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (74, 'FI', 'Finland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (75, 'FR', 'France',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (76, 'GF', 'French Guiana',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (77, 'PF', 'French Polynesia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (78, 'TF', 'French Southern Territories',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (79, 'GA', 'Gabon',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (80, 'GM', 'Gambia The',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (81, 'GE', 'Georgia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (82, 'DE', 'Germany',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (83, 'GH', 'Ghana',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (84, 'GI', 'Gibraltar',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (85, 'GR', 'Greece',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (86, 'GL', 'Greenland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (87, 'GD', 'Grenada',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (88, 'GP', 'Guadeloupe',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (89, 'GU', 'Guam',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (90, 'GT', 'Guatemala',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (91, 'XU', 'Guernsey and Alderney',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (92, 'GN', 'Guinea',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (93, 'GW', 'Guinea-Bissau',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (94, 'GY', 'Guyana',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (95, 'HT', 'Haiti',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (96, 'HM', 'Heard and McDonald Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (97, 'HN', 'Honduras',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (98, 'HK', 'Hong Kong S.A.R.',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (99, 'HU', 'Hungary',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (100, 'IS', 'Iceland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (101, 'IN', 'India',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (102, 'ID', 'Indonesia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (103, 'IR', 'Iran',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (104, 'IQ', 'Iraq',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (105, 'IE', 'Ireland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (106, 'IL', 'Israel',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (107, 'IT', 'Italy',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (108, 'JM', 'Jamaica',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (109, 'JP', 'Japan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (110, 'XJ', 'Jersey',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (111, 'JO', 'Jordan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (112, 'KZ', 'Kazakhstan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (113, 'KE', 'Kenya',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (114, 'KI', 'Kiribati',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (115, 'KP', 'Korea North',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (116, 'KR', 'Korea South',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (117, 'KW', 'Kuwait',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (118, 'KG', 'Kyrgyzstan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (119, 'LA', 'Laos',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (120, 'LV', 'Latvia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (121, 'LB', 'Lebanon',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (122, 'LS', 'Lesotho',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (123, 'LR', 'Liberia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (124, 'LY', 'Libya',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (125, 'LI', 'Liechtenstein',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (126, 'LT', 'Lithuania',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (127, 'LU', 'Luxembourg',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (128, 'MO', 'Macau S.A.R.',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (129, 'MK', 'Macedonia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (130, 'MG', 'Madagascar',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (131, 'MW', 'Malawi',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (132, 'MY', 'Malaysia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (133, 'MV', 'Maldives',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (134, 'ML', 'Mali',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (135, 'MT', 'Malta',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (136, 'XM', 'Man (Isle of)',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (137, 'MH', 'Marshall Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (138, 'MQ', 'Martinique',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (139, 'MR', 'Mauritania',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (140, 'MU', 'Mauritius',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (141, 'YT', 'Mayotte',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (142, 'MX', 'Mexico',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (143, 'FM', 'Micronesia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (144, 'MD', 'Moldova',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (145, 'MC', 'Monaco',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (146, 'MN', 'Mongolia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (147, 'MS', 'Montserrat',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (148, 'MA', 'Morocco',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (149, 'MZ', 'Mozambique',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (150, 'MM', 'Myanmar',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (151, 'NA', 'Namibia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (152, 'NR', 'Nauru',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (153, 'NP', 'Nepal',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (154, 'AN', 'Netherlands Antilles',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (155, 'NL', 'Netherlands The',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (156, 'NC', 'New Caledonia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (157, 'NZ', 'New Zealand',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (158, 'NI', 'Nicaragua',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (159, 'NE', 'Niger',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (160, 'NG', 'Nigeria',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (161, 'NU', 'Niue',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (162, 'NF', 'Norfolk Island',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (163, 'MP', 'Northern Mariana Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (164, 'NO', 'Norway',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (165, 'OM', 'Oman',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (166, 'PK', 'Pakistan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (167, 'PW', 'Palau',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (168, 'PS', 'Palestinian Territory Occupied',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (169, 'PA', 'Panama',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (170, 'PG', 'Papua new Guinea',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (171, 'PY', 'Paraguay',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (172, 'PE', 'Peru',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (173, 'PH', 'Philippines',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (174, 'PN', 'Pitcairn Island',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (175, 'PL', 'Poland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (176, 'PT', 'Portugal',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (177, 'PR', 'Puerto Rico',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (178, 'QA', 'Qatar',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (179, 'RE', 'Reunion',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (180, 'RO', 'Romania',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (181, 'RU', 'Russia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (182, 'RW', 'Rwanda',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (183, 'SH', 'Saint Helena',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (184, 'KN', 'Saint Kitts And Nevis',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (185, 'LC', 'Saint Lucia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (186, 'PM', 'Saint Pierre and Miquelon',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (187, 'VC', 'Saint Vincent And The Grenadines',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (188, 'WS', 'Samoa',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (189, 'SM', 'San Marino',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (190, 'ST', 'Sao Tome and Principe',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (191, 'SA', 'Saudi Arabia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (192, 'SN', 'Senegal',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (193, 'RS', 'Serbia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (194, 'SC', 'Seychelles',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (195, 'SL', 'Sierra Leone',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (196, 'SG', 'Singapore',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (197, 'SK', 'Slovakia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (198, 'SI', 'Slovenia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (199, 'XG', 'Smaller Territories of the UK',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (200, 'SB', 'Solomon Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (201, 'SO', 'Somalia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (202, 'ZA', 'South Africa',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (203, 'GS', 'South Georgia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (204, 'SS', 'South Sudan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (205, 'ES', 'Spain',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (206, 'LK', 'Sri Lanka',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (207, 'SD', 'Sudan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (208, 'SR', 'Suriname',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (209, 'SJ', 'Svalbard And Jan Mayen Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (210, 'SZ', 'Swaziland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (211, 'SE', 'Sweden',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (212, 'CH', 'Switzerland',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (213, 'SY', 'Syria',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (214, 'TW', 'Taiwan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (215, 'TJ', 'Tajikistan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (216, 'TZ', 'Tanzania',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (217, 'TH', 'Thailand',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (218, 'TG', 'Togo',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (219, 'TK', 'Tokelau',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (220, 'TO', 'Tonga',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (221, 'TT', 'Trinidad And Tobago',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (222, 'TN', 'Tunisia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (223, 'TR', 'Turkey',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (224, 'TM', 'Turkmenistan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (225, 'TC', 'Turks And Caicos Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (226, 'TV', 'Tuvalu',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (227, 'UG', 'Uganda',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (228, 'UA', 'Ukraine',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (229, 'AE', 'United Arab Emirates',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (230, 'GB', 'United Kingdom',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (231, 'US', 'United States',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (232, 'UM', 'United States Minor Outlying Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (233, 'UY', 'Uruguay',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (234, 'UZ', 'Uzbekistan',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (235, 'VU', 'Vanuatu',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (236, 'VA', 'Vatican City State (Holy See)',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (237, 'VE', 'Venezuela',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (238, 'VN', 'Vietnam',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (239, 'VG', 'Virgin Islands (British)',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (240, 'VI', 'Virgin Islands (US)',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (241, 'WF', 'Wallis And Futuna Islands',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (242, 'EH', 'Western Sahara',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (243, 'YE', 'Yemen',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (244, 'YU', 'Yugoslavia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (245, 'ZM', 'Zambia',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
DB::statement("INSERT INTO countries (id,sortname,country_name, created_at, updated_at) VALUES (246, 'ZW', 'Zimbabwe',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");


    }
}
